# Generated by Django 4.2.24 on 2025-11-11 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BinSignal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('led_color', models.TextField(blank=True, db_column='ledColor', null=True)),
                ('mode_blynk', models.TextField(blank=True, db_column='modeBlynk', null=True)),
                ('created_add', models.DateField(blank=True, db_column='createdAdd', null=True)),
            ],
            options={
                'db_table': 'bin_signal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RefItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ext_id', models.TextField()),
                ('name', models.TextField(null=True, unique=True)),
                ('bar_code', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ref_items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RefSize',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('ext_id', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ref_size',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TechUnit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tech_unit',
                'managed': False,
            },
        ),
    ]
