# Generated by Django 4.2.24 on 2026-01-16 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_binsignal_refitem_refsize_techunit'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bin',
            table='IH_bin',
        ),
    ]
