# Generated by Django 4.2.24 on 2026-01-16 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_bin_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='binsignal',
            table='IH_bin_signal',
        ),
        migrations.AlterModelTable(
            name='rack',
            table='IH_rack',
        ),
        migrations.AlterModelTable(
            name='refitem',
            table='IH_ref_items',
        ),
        migrations.AlterModelTable(
            name='refsize',
            table='IH_ref_size',
        ),
        migrations.AlterModelTable(
            name='shelf',
            table='IH_shelf',
        ),
        migrations.AlterModelTable(
            name='techunit',
            table='IH_tech_unit',
        ),
        migrations.AlterModelTable(
            name='warehouse',
            table='IH_site',
        ),
    ]
