# Generated by Django 4.2.24 on 2026-01-16 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_binsignal_table_alter_rack_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='shelf',
            table='shelf',
        ),
    ]
