# Generated by Django 4.2.24 on 2026-01-21 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_shelf_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_column='created_at')),
                ('operation', models.TextField(db_column='operation')),
                ('source', models.TextField(db_column='source')),
                ('message', models.TextField(db_column='message')),
                ('user', models.TextField(blank=True, db_column='user', null=True)),
            ],
            options={
                'db_table': '"IH_LOG"',
                'ordering': ['id'],
                'managed': False,
            },
        ),
    ]
