# Generated by Django 4.2.24 on 2026-01-21 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_oplog'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='oplog',
            table='IH_LOG',
        ),
    ]
