# Generated by Django 4.2.24 on 2026-02-02 06:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_oplog_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='IHFileSelect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.TextField()),
                ('sha256', models.CharField(blank=True, max_length=64, null=True)),
                ('size_bytes', models.BigIntegerField()),
                ('uploaded_by', models.TextField(blank=True, null=True)),
                ('workstation_id', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('uploaded', 'uploaded'), ('parsed', 'parsed'), ('active', 'active'), ('error', 'error'), ('archived', 'archived')], default='uploaded', max_length=16)),
                ('error_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parsed_at', models.DateTimeField(blank=True, null=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'IH File Select',
                'verbose_name_plural': 'IH File Select',
                'db_table': 'IH_File_Select',
                'indexes': [models.Index(fields=['status'], name='IH_File_Sel_status_514e81_idx'), models.Index(fields=['created_at'], name='IH_File_Sel_created_b90f2f_idx'), models.Index(fields=['uid'], name='IH_File_Sel_uid_db77cb_idx'), models.Index(fields=['sha256'], name='IH_File_Sel_sha256_1de49c_idx')],
            },
        ),
    ]
