# Generated by Django 4.2.24 on 2026-02-02 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_ihfileselect'),
    ]

    operations = [
        migrations.AddField(
            model_name='ihfileselect',
            name='stored_path',
            field=models.TextField(blank=True, null=True),
        ),
    ]
