# Generated by Django 4.2.24 on 2026-02-26 05:07

from django.db import migrations, models
import pages.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_ihfileselect_stored_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='ihfileselect',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=pages.models.select_upload_to),
        ),
    ]
